spring:
  threads:
    virtual:
      enabled: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:rabbit}
    password: ${RABBIT_PASSWORD:rabbit}
server:
  port: 3055